# Generated by Django 6.0.1 on 2026-01-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myprofile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="proficiency_level",
        ),
        migrations.AddField(
            model_name="award",
            name="award_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="certification",
            name="do_expire",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="education",
            name="focus",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="institution_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="experience",
            name="company_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="is_alone",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="is_finished",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="project",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="months_of_experience",
            field=models.FloatField(
                blank=True,
                help_text="Total months of experience with this skill",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="self_assesment_percent",
            field=models.IntegerField(
                blank=True, help_text="Enter a value between 0 and 100", null=True
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="type",
            field=models.CharField(
                choices=[
                    ("technical", "Technical"),
                    ("soft", "Soft"),
                    ("language", "Language"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="proficiency_level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("basic", "Basic"),
                    ("medium", "Medium"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                    ("native", "Native Speaker"),
                ],
                max_length=50,
            ),
        ),
    ]
